# Generated by Django 5.0.6 on 2024-06-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_create_at_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='redirect_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(null=True),
        ),
    ]
