# Generated by Django 5.0.6 on 2024-06-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_redirect_url_alter_payment_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='webhook_url',
            field=models.URLField(null=True),
        ),
    ]
