# Generated by Django 5.0.6 on 2024-06-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_paymentnotifications'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentnotifications',
            table='payment_notifications',
        ),
    ]
