# Generated by Django 5.0.6 on 2024-06-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_paymentnotifications_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentnotifications',
            name='type',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
