# Generated by Django 5.0.6 on 2024-07-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_paymentnotifications_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.BooleanField(),
        ),
    ]
